project:
  type: website
  output-dir: docs

execute: 
  echo: true
  freeze: auto
  keep-md: false

  
website:
  title: "Kaizen and Advanced Manufacturing Research"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - research_2024.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/factorialmap
      - icon: github
        href: https://github.com/factorialmap/kaizen-advm
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Marcelo Carvalho  dos Anjos"

format:
  html:
    theme: flatly
    toc: true
    code-fold: true
    
editor: source

