project:
  type: website
  output-dir: docs

execute: 
  echo: true
  freeze: auto
  keep-md: false

  
website:
  title: "Kaizen & Advanced Manufacturing"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - workflow.qmd
      - sidebar:research_2024
  sidebar: 
    - id: research_2024
      title: "Research 2024"
      collapse-level: 7
      contents: 
        - href: calendar.qmd
        - href: action-plan-us-advm.qmd
        - href: mit-course-advm.qmd
        - href: research-us-mfg.qmd
        - href: data-analysis-mfg.qmd
        - href: macroeconomic.qmd
        - href: three-generations.qmd
      tools:
      - icon: twitter
        href: https://twitter.com/factorialmap
      - icon: github
        href: https://github.com/factorialmap/kaizen-advm
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Marcelo Carvalho  dos Anjos"

format:
  html:
    theme: flatly
    toc: true
    code-fold: true
    
editor: source
