---
title: "Calendar"
execute: 
  warning: false
  echo: false
---

### [Calendar 2024]{style="color: #9D0F6A ;"}

```{r}
#| fig-width: 8
#| fig-height: 6

library(tidyverse)
library(ganttrify)

data_gantt <- readxl::read_xlsx("C:/Users/Usuario/OneDrive/models/quarto_projects/db/gantt_research24.xlsx", sheet = 1)
data_spot <- readxl::read_xlsx("C:/Users/Usuario/OneDrive/models/quarto_projects/db/gantt_research24.xlsx", sheet = 2)


#make gantt chart
ganttrify(
  project = data_gantt,
  spots = data_spot,
  spot_size_text_relative = 1,
  spot_fill = ggplot2::alpha(c("white"), 0.1),
  spot_padding = unit(0.1, "lines"),
  spot_border = NA,
  project_start_date = "2024-01",
  #hide_wp = TRUE,
  alpha_wp = 0.5,
  alpha_activity = 0.8,
  line_end_wp = "round",
  line_end_activity = "round",
  size_text_relative = .9,
  mark_quarters = TRUE,
  font_family = "Roboto Condensed",
  axis_text_align = "left"
) +
  labs(title = "Immigration process and ongoing activities",
       subtitle = "2024 - Marcelo Carvalho",
       caption = "@carvalhoribeiro | USCIS/NVC data")
```

### [Activity details]{style="color: #9D0F6A ;"}

-   **1.1. Additive Mfg MIT - Intro:** Classes about design and 3D printing using metal, plastics among other materials

-   **1.2. Advc Data Analytics MIT - Intro:** Classes about industry driven problem solving using IoT, data, machine learning/deep learning models and statistical process control.

-   **1.3. Translate my book to Engish:** Translate my book "PDCA and quality tools" from portuguese to english language.

-   **1.4. Lean Six Sigma Methods - MIT:** Classes about lean manufaturing to training lean principles applied to specific problems, english language, data, and references.

-   **1.5.Create website portfolio & research:** This is the website we are now, and it contains updated information about projects, macroeconomic and operational data that I use in my day-to-day work, and also the study I am doing on the document Action Plan for U.S. Leadership in Advanced Manufacturing.

-   **1.6. Monitoring Invest America mfg:** News(YouTube, X, CBS News, CNBC, Bloomberg) about the construction stages of manufacturing plants such as Microsoft, Toyota, SK, Samsung, Tesla, Our Next Energy, Texas Instruments among others.

-   **1.7. Day-to-day at Mfg (Reddit ,YT &X):** Study on the problems encountered in day-to-day manufacturing processes in the U.S., such as negotiation with suppliers, concepts such as TCO(total cost of ownership), trade agreements between countries, logistics, tariffs, MFN (Most Favored Nation) status with the destination country, etc.

-   **1.8. Job Offers research(Boston Area):** Research on skills required by companies in the Boston area.

-   **2.1. Notification I-797C:** Notifications

-   **2.2. Job market research:** Analysis of job offers in the process improvement available in the Boston area.

-   **2.3. House Boston area research:** Analysis of available housing in the Boston area.

-   **2.4. Route Apt to MIT/Acropolis study:** Analysis of distances, routes, available public transportation, and travel time from the neighborhood to the MIT and New Acropolis Boston schools.

-   **3.1. Notification USCIS I-797:** Important Notification

-   **3.2. 3.3. 3.4. Contact MIT Professors:** Contact with Professors to reinforce my interest in workforce-oriented courses at MIT and continuing philisophy courses at New Acropolis Boston.

-   **3.5. Contact House Boston area:** Research the conditions and prices for housing rentals in the Boston area.

-   **4.1. Notification NVC:** Important Notification

-   **4.2. DS260 completed:** Submission of documents

-   **4.3. Collect civil documents:** Request and collection of civil documents

-   **4.4. Contacting NVC:**

-   **4.5. Civil docs were sent:**

-   **4.6. Additional info requested:** Full birth certificate (inteiro teor)

-   **4.7. Full BC requested for civil registry office:**
