---
title: "Past, Present, and Future of Manufacturing in US"
---

**Past**

-   Industrial revolution 1865, Carnegie, bessemer process etc.

-   Ford, Packard, WWII, Inovations, Deming

-   Exit Zero, American Story, Rust Belt - First Impressions, Rust Belt - City's economic Struggle

-   Introduction to Lean Six Sigma Methods by MIT Aeronautics Engineering System Division

**Present**

-   Chips and Science Act and Research and Development, Competition, and Innovation Ac

-   Inflation Reduction Act

-   Invest in America

-   Workforce Education

-   Action plan for Manufacturing in US

**Future**

-   Consistence and Competitiveness on Manufacturing

-   Personal Finance

-   Manufacturing base


**Energy Storage**


**Past**

- Boston Power lithium ion battery technologies




**Present**

- Ambitious of industrialize, build the factories, Supply chain, and vertically integrate  those Supply chains together. 

- Our Next Energy raised capital of 1B+ to generate 20 GWh for battery.

- 


**Future**

-   Consistence and Competitiveness on Manufacturing

